--- !!perl/hash:AI::Perceptron::Simple
attributes_hash_ref:
  black_shades: 11.3153
  blue_shades: 11.8153
  brown_shades: 43.3153
  female_present: 65.8153
  flower_coverage_more_than_half: 13.8153
  green_shades: 16.8153
  has_bronze_items: 0.8153
  has_fancy_stuff: 31.3153
  has_flowers: 23.8153
  has_gold_items: -0.6847
  has_leaves: 12.3153
  has_obvious_inanimate_objects: -6.6847
  has_other_living_things: 37.3153
  has_silver_items: 15.8153
  has_trees: -11.1847
  leaves_coverage_more_than_half: 0.8153
  male_present: -15.1847
  orange_shades: 26.8153
  overall_black_dominant: 0.8153
  overall_blue_dominant: 22.3153
  overall_brown_dominant: -2.1847
  overall_green_dominant: 28.3153
  overall_orange_dominant: 0.8153
  overall_pink_dominant: -1.1847
  overall_purple_dominant: -2.1847
  overall_red_dominant: 0.8153
  overall_white_dominant: 20.3153
  overall_yellow_dominant: 5.3153
  purple_shades: 23.3153
  red_shades: 39.3153
  title_decoration_very_fancy: -3.6847
  title_multiple_colors: -18.1847
  title_towards_SongTi: 56.3153
  total_people_1: 57.3153
  total_people_2: 14.8153
  total_people_3: -4.6847
  total_people_4: 0.8153
  total_people_5_n_above: 0.8153
  trees_coverage_more_than_half: 0.8153
  yellow_shades: 30.8153
learning_rate: 0.5
threshold: 320
